Repository kora-projects/kora, pull requests merged in 2024-12, with the labels that each got.

#202 Grpc client telemetry should work correctly on request cancellation
  grpc/grpc-client/src/main/java/ru/tinkoff/grpc/client/telemetry/GrpcClientTelemetryInterceptor.java
Labels: bug, module: grpc, module: telemetry

#203 Config boolean as native type
  config/config-annotation-processor/src/main/java/ru/tinkoff/kora/config/annotation/processor/ConfigParserGenerator.java
  config/config-annotation-processor/src/main/java/ru/tinkoff/kora/config/annotation/processor/ConfigUtils.java
  config/config-annotation-processor/src/test/java/ru/tinkoff/kora/config/annotation/processor/AnnotationConfigTest.java
  config/config-symbol-processor/src/main/kotlin/ru/tinkoff/kora/config/ksp/ConfigParserGenerator.kt
  config/config-symbol-processor/src/test/kotlin/ru/tinkoff/kora/config/symbol/processor/AnnotationConfigTest.kt
  grpc/grpc-client-annotation-processor/src/test/java/ru/tinkoff/grpc/client/annotation/processor/GrpcClientExtensionTest.java
  grpc/grpc-client-symbol-processor/src/test/kotlin/ru/tinkoff/grpc/client/ksp/GrpcClientExtensionTest.kt
  http/http-client-annotation-processor/src/test/java/ru/tinkoff/kora/http/client/annotation/processor/AbstractHttpClientTest.java
  http/http-client-symbol-processor/src/test/kotlin/ru/tinkoff/kora/http/client/symbol/processor/AbstractHttpClientTest.kt
  scheduling/scheduling-quartz/src/test/java/ru/tinkoff/kora/scheduling/quartz/KoraQuartzJobRegistrarTest.java
Labels: optimization

#205 HttpServer private release sleep removed
  http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowHttpServer.java
  http/http-server-undertow/src/main/java/ru/tinkoff/kora/http/server/undertow/UndertowPrivateHttpServer.java
Labels: module: http, optimization

#206 ResourceConfigOrigin#description fixed
  config/config-common/src/main/java/ru/tinkoff/kora/config/common/origin/ResourceConfigOrigin.java
Labels: minor, module: core

#210 Template components matching fix for java graph processor
  annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/CompileResult.java
  kora-app-annotation-processor/src/main/java/ru/tinkoff/kora/kora/app/annotation/processor/ComponentTemplateHelper.java
  kora-app-annotation-processor/src/test/java/ru/tinkoff/kora/kora/app/annotation/processor/ComponentTemplatesTest.java
  kora-app-symbol-processor/src/test/kotlin/ru/tinkoff/kora/kora/app/ksp/ComponentTemplatesTest.kt
  symbol-processor-common/src/testFixtures/kotlin/ru/tinkoff/kora/ksp/common/AbstractSymbolProcessorTest.kt
Labels: bug, module: core
